
name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Install grpc_tools
      run: pip install grpcio-tools

    - name: Generate Python Stubs
      run: |
        mkdir python
        python -m grpc_tools.protoc -I. --python_out=python --grpc_python_out=python *.proto

    - name: Commit Back To Repo
      uses: stefanzweifel/git-auto-commit-action@v4


